### ISSUE TITLE
Не патчится

### ISSUE THREAD

**Issue by korney4eg** [vnaum/FTL-rus#1]
Пишет ошибку: 
Patching failed: java.nio.charset.MalformedInputException: Input length = 1

Больше ничего. FLT:AE

**Comment by vnaum** [comment]
Пожалуй что и не заработает никогда.
FTL:AE вышел, времени проехать все тексты наново нету, Grognak's Mod Manager устарел (и патчишь ты явно не им).
На рутрекере есть виндовые сборки из которых выковыриваются моды.
https://rutracker.org/forum/viewtopic.php?t=5531678
